// Auto-generated column positions for OSD settings menu
// Generated by generate_column_positions.py

#ifndef __MENU_COLUMN_POSITIONS_H__
#define __MENU_COLUMN_POSITIONS_H__

// Pre-computed value column positions for each category
// Based on longest setting name + 2 chars, constrained to usable width (26 chars)
static const int category_value_column_pos[] = {
    19, // CAT_VIDEO_DISPLAY
    18, // CAT_AUDIO
    12, // CAT_INPUT_CONTROLLERS
    22, // CAT_SYSTEM_BOOT
    12, // CAT_NETWORK_STORAGE
    13, // CAT_ADVANCED
};

// Longest setting name length per category (for reference)
static const int category_longest_name[] = {
    17, // CAT_VIDEO_DISPLAY
    16, // CAT_AUDIO
    0, // CAT_INPUT_CONTROLLERS
    20, // CAT_SYSTEM_BOOT
    0, // CAT_NETWORK_STORAGE
    11, // CAT_ADVANCED
};

#endif // __MENU_COLUMN_POSITIONS_H__

/* Analysis Results:

CAT_ADVANCED:
  OSD menu settings: 1
  Longest setting name: 11 chars
  Value column position: 13
  Top longest names:
    11: "Keyrah Mode"

CAT_AUDIO:
  OSD menu settings: 1
  Longest setting name: 16 chars
  Value column position: 18
  Top longest names:
    16: "HDMI 96kHz Audio"

CAT_SYSTEM_BOOT:
  OSD menu settings: 4
  Longest setting name: 20 chars
  Value column position: 22
  Top longest names:
    20: "Framebuffer Terminal"
    16: "Framebuffer Size"
    13: "Menu PAL Mode"

CAT_VIDEO_DISPLAY:
  OSD menu settings: 11
  Longest setting name: 17 chars
  Value column position: 19
  Top longest names:
    17: "Force Scandoubler"
    17: "VGA Sync-on-Green"
    17: "Video Mode (NTSC)"

*/